// <auto-generated />
namespace EF6_QueryTaker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Query_Category_Comment_user_from : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Query_Category_Comment_user_from));
        
        string IMigrationMetadata.Id
        {
            get { return "202404071113555_Query_Category_Comment_user_from"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
